description: Custom input processor for acceleration

compatible: "zmk,input-processor-acceleration"

include: base.yaml

properties:
  acceleration-exponent:
    type: int
    required: true

  acceleration-coefficient:
    type: int
    required: true

# 🔥 반드시 이렇게
input-processor-cells: []
