description: Custom input processor for acceleration

compatible: "zmk,input-processor-acceleration"

include: base.yaml

properties:
  acceleration-exponent:
    type: int
    required: true

  acceleration-coefficient:
    type: int
    required: true

# 🔥 이거 없으면 지금처럼 터짐
input-processor-cells: 0
