manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    # urob 원격지 설정은 삭제해도 됩니다.

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    # 아래와 같이 'url' 전체를 직접 적어주세요.
    - name: zmk-input-behavior-listener
      url: https://github.com/urob/zmk-input-behavior-listener
      revision: main

  self:
    path: config
