manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    # 수정된 부분: url을 직접 입력하고 remote 설정을 뺍니다.
    - name: zmk-input-behavior-listener
      url: https://github.com/urob/zmk-input-behavior-listener
      revision: main

  self:
    path: config
